// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvbxmnyxkmhwyfjppsoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Ynhtbnl4a21od3lmanBwc29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4ODg3MDcsImV4cCI6MjA1MjQ2NDcwN30.sKtBMH0DBoLHrzK1VUdzHJEu4CpTnkanOdu-P4ebBWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);